episode 0
Simulating
Selected Action: 5 with ratios [5, 9, 5, 9]
Selected Action: 8 with ratios [10, 6, 6, 6]
Selected Action: 7 with ratios [4, 8, 8, 8]
Selected Action: 7 with ratios [4, 8, 8, 8]
Selected Action: 9 with ratios [9, 5, 5, 9]
Selected Action: 10 with ratios [9, 5, 9, 5]
Selected Action: 1 with ratios [6, 6, 6, 10]
Selected Action: 13 with ratios [8, 8, 4, 8]
Selected Action: 11 with ratios [8, 4, 8, 8]
Selected Action: 11 with ratios [8, 4, 8, 8]
Selected Action: 7 with ratios [4, 8, 8, 8]
Selected Action: 13 with ratios [8, 8, 4, 8]
Selected Action: 10 with ratios [9, 5, 9, 5]
Selected Action: 10 with ratios [9, 5, 9, 5]
Selected Action: 13 with ratios [8, 8, 4, 8]
Selected Action: 0 with ratios [7, 7, 7, 7]
Selected Action: 14 with ratios [8, 8, 8, 4]
Selected Action: 3 with ratios [5, 5, 9, 9]
Selected Action: 10 with ratios [9, 5, 9, 5]
Selected Action: 0 with ratios [7, 7, 7, 7]
Selected Action: 2 with ratios [6, 6, 10, 6]
Selected Action: 3 with ratios [5, 5, 9, 9]
Selected Action: 1 with ratios [6, 6, 6, 10]
Selected Action: 2 with ratios [6, 6, 10, 6]
Selected Action: 4 with ratios [6, 10, 6, 6]
Traceback (most recent call last):
  File "C:\Users\admin\cycletsc\traffic_light_control_DQN\training_main.py", line 86, in <module>
    Simulation.run(episode, epsilon)
  File "C:\Users\admin\cycletsc\traffic_light_control_DQN\simulation.py", line 177, in run
    self._simulate(duration)
  File "C:\Users\admin\cycletsc\traffic_light_control_DQN\simulation.py", line 244, in _simulate
  File "C:\Users\admin\anaconda3\lib\site-packages\traci\main.py", line 198, in simulationStep
    connection.check().simulationStep(step)
  File "C:\Users\admin\anaconda3\lib\site-packages\traci\connection.py", line 368, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "C:\Users\admin\anaconda3\lib\site-packages\traci\connection.py", line 231, in _sendCmd
    return self._sendExact()
  File "C:\Users\admin\anaconda3\lib\site-packages\traci\connection.py", line 137, in _sendExact
    raise FatalTraCIError("Connection closed by SUMO.")
traci.exceptions.FatalTraCIError: Connection closed by SUMO.